[workspace]
members = [
    "protoc",
    "protoc-rust",
    "protobuf",
    "protobuf-codegen",
    "protobuf-codegen-pure",
    "protobuf-codegen-pure-test",
    "protobuf-test",
    "protobuf-test-common",
    "protoc/test-protoc",
]
